### ISSUE TITLE
Lines with ::class constant are not covered

### ISSUE THREAD

**Issue by ingowalther** [sebastianbergmann/php-code-coverage#793]
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.1.3
| PHP version               | 7.4.3
| Driver                    | Xdebug and pcov
| Xdebug version (if used)  | 2.9.2
| pcov version | 1.0.6
| Installation Method       | PHPUnit PHAR
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.3.7

Since the Update to PHPUnit 9.3.7 the Coverage-Report does not contain all lines.

Since the update the report looks like this (line 115 is missing): 
![image](https://user-images.githubusercontent.com/7096553/90121818-c16b8400-dd5c-11ea-97ee-7ded0f1f2c3e.png)

Before it looked like this (line 115 is covered):
![Screenshot_2020-08-13_12-05-54](https://user-images.githubusercontent.com/7096553/90122384-7e5de080-dd5d-11ea-87d5-6e64225a3830.png)

Before the Update the PHPUnit PHAR was used in Version 9.2.6

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
Also, please test with recent versions of PHP and Xdebug. php-code-coverage no longer works around bug in Xdebug, for instance, that have been fixed in newer versions.

**Comment by ingowalther** [comment]
This behavior always occurs when "XXX::class" is used.
![image](https://user-images.githubusercontent.com/7096553/90140712-69437a80-dd7a-11ea-8e1f-958b3704597d.png)

I checked the behavior again with PHP 7.4.9 and Xdebug 2.9.6 and the problem is still there.

Here is  my minimal test case:
[minimal-test-case.zip](https://github.com/sebastianbergmann/php-code-coverage/files/5069345/minimal-test-case.zip)

**Comment by sebastianbergmann** [comment]
CC @derickr @dvdoug

**Comment by dvdoug** [comment]
OK, that's gonna be the same as #794 then

**Comment by dvdoug** [comment]
And I'm going to put money on https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/StaticAnalysis/ParsingCoveredFileAnalyser.php#L216 not working the same as when the same workaround was used under PHP_Token_Stream.

**Comment by sebastianbergmann** [comment]
You're probably right, I'll have a look. Thanks for the pointer!

**Comment by dvdoug** [comment]
Yeah before this construct was identified as PHP_Token_CLASS_NAME_CONSTANT so wasn't affected

**Comment by sebastianbergmann** [comment]
Can you please test with 081faa0834dee80268716e5c43f941ce8b3a975b? Thanks!

**Comment by ingowalther** [comment]
I can confirm that the problem no longer occurs!

Thank you very much!

**Comment by dominikzogg** [comment]
tested #794 with phpdbg, its also fixed with this commit, thank you @sebastianbergmann
